### ISSUE TITLE
ProcessEnv userShellInvocation can’t handle spaces

### ISSUE THREAD

**Issue by wjk** [ChimeHQ/ProcessEnv#2]
One of the great things about Unix-like systems as compared to Windows is that arguments are passed as separate strings. On Windows, every program must properly shell-quote the values; to do so wrong is a security hole.

I understand how you need to run a command through the user’s shell. I understand how `sh -c` requires the full command as only one argument. However, were any of the original arguments to contain spaces, they would be evaluated by the shell as multiple arguments instead of one. If the user has a project in a path with a space in it, ProcessEnv will malfunction. Some quoting is needed here.

**Comment by mattmassicotte** [comment]
Yup I'm pretty sure you are right. Should be easy to expose in a test and address. Thank you very much for the report!

**Comment by mattmassicotte** [comment]
Fixed with https://github.com/ChimeHQ/ProcessEnv/commit/4055e58eb5d20501ffa02030f429614e8d3f50c5
